### ISSUE TITLE
Add Self-Destructing Cookies features

### ISSUE THREAD

**Issue by davidhedlund** [darktrojan/cookietime#5]
> [Self-Destructing Cookies](https://addons.mozilla.org/en-US/firefox/addon/self-destructing-cookies/): "Fix the web. Gets rid of a site's cookies and LocalStorage as soon as you close its tabs. Protects against trackers and zombie-cookies. Trustworthy services can be whitelisted."

Self-Destructing Cookies is not a web extension and the author just said to me that he don't have time for that either. The only web extension add-on I found that can delete cookies is **Cookie Time**!

So can you please implement the "Gets rid of a site's cookies and LocalStorage as soon as you close its tabs." feature in Self-Destructing Cookies?

**Comment by davidhedlund** [comment]
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by darktrojan** [comment]
Cookie Time isn't a web extension either. Even if it was I would be unlikely to add those features.

**Comment by davidhedlund** [comment]
@darktrojan Cookie Time is multiprocess compatible at least says Mozilla's **Add-on Compatibility Reporter**.

**Comment by darktrojan** [comment]
That is correct, but doesn't make it a web extension (they're not the same thing), so it'll be going away when Firefox 57 comes along.
