### ISSUE TITLE
"deleted NaN cookies"

### ISSUE THREAD

**Issue by Jan02** [darktrojan/cookietime#7]
After you click "run now", the dialog says "deleted NaN cookies".
![ct](https://framapic.org/rbU2pdawqTyb/sAV9BdAJMnnY)

**Comment by gmariani** [comment]
![screenshot 2017-05-21 23 02 00](https://cloud.githubusercontent.com/assets/5058619/26291347/9dfc48c0-3e7b-11e7-8ad4-f3db3b2ba9a7.png)
Still not fixed

**Comment by darktrojan** [comment]
Is the pref `extensions.cookietime.deleteUnused.days` one of 7, 14, 30, 60, 91, 182, 273, 365, or 547?

**Comment by gmariani** [comment]
It is 90
![screenshot 2017-05-22 07 32 00](https://cloud.githubusercontent.com/assets/5058619/26306293/cc0aff8c-3ec0-11e7-8baf-8efaab864515.png)

**Comment by darktrojan** [comment]
Yeah, that's a bug. The default should be 91, but it's 90 for some reason. Changing the options will fix it, as will the new version I'm working on now to actually count what was deleted.
